name: tilawa_lock
description: Tilawa Lock – Recite to Unlock
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  permission_handler: ^11.3.0
  flutter_overlay_window: ^0.4.2
  http: ^1.2.0
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  device_apps: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/AppLogo/applogo.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#ffffff"
  image: assets/AppLogo/applogo.png
  android: true
  ios: true

  android_12:
    image: assets/AppLogo/applogo.png
    color: "#ffffff"
